name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:

  build:
    name: Test Solution Cases
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      id: go
    - name: Get dependencies
      run:  go mod download
    - name: Test Solutions
      run: make test
